export const UNIVERSITY = {
  name: {
    kk: 'О.А. Байқоңыров атындағы Жезқазған университеті',
    ru: 'Жезказганский университет им. О.А. Байконурова',
    en: 'O.A. Baikonurov Zhezkazgan University',
  },
  shortName: 'ZhezU',
  phone: '+7 (7102) 72-40-00',
  email: 'info@zhezu.edu.kz',
  address: {
    kk: '100600, Жезқазған қ., Байқоңыров к-сі, 6А',
    ru: '100600, г. Жезказган, ул. Байконурова, 6А',
    en: '6A Baikonurov St., Zhezkazgan, 100600',
  },
  website: 'https://zhezu.edu.kz',
  social: {
    instagram: 'https://instagram.com/zhezu_university',
    facebook: 'https://facebook.com/zhezu.university',
    youtube: 'https://youtube.com/@zhezu',
    telegram: 'https://t.me/zhezu_university',
  },
  stats: {
    students: 5000,
    programs: 52,
    employmentRate: 87,
    yearsOfExperience: 28,
  },
} as const;

export const PROGRAMS = [
  {
    id: 'cs',
    faculty: 'it',
    degree: 'bachelor',
    credits: 240,
    duration: 4,
    languages: ['kk', 'ru'],
    name: { kk: 'Информатика', ru: 'Информатика', en: 'Computer Science' },
    description: {
      kk: 'Бағдарламалау, алгоритмдер, деректер базасы және жасанды интеллект негіздері.',
      ru: 'Программирование, алгоритмы, базы данных и основы искусственного интеллекта.',
      en: 'Programming, algorithms, databases, and fundamentals of artificial intelligence.',
    },
  },
  {
    id: 'economics',
    faculty: 'business',
    degree: 'bachelor',
    credits: 240,
    duration: 4,
    languages: ['kk', 'ru'],
    name: { kk: 'Экономика', ru: 'Экономика', en: 'Economics' },
    description: {
      kk: 'Микро және макроэкономика, қаржы, статистика және бизнес-жоспарлау.',
      ru: 'Микро- и макроэкономика, финансы, статистика и бизнес-планирование.',
      en: 'Micro and macroeconomics, finance, statistics, and business planning.',
    },
  },
  {
    id: 'mining',
    faculty: 'engineering',
    degree: 'bachelor',
    credits: 240,
    duration: 4,
    languages: ['kk', 'ru'],
    name: { kk: 'Тау-кен ісі', ru: 'Горное дело', en: 'Mining Engineering' },
    description: {
      kk: 'Кен орындарын игеру, тау-кен машиналары және пайдалы қазбаларды өңдеу технологиялары.',
      ru: 'Разработка месторождений, горные машины и технологии переработки полезных ископаемых.',
      en: 'Deposit development, mining machinery, and mineral processing technologies.',
    },
  },
  {
    id: 'pedagogy',
    faculty: 'education',
    degree: 'bachelor',
    credits: 240,
    duration: 4,
    languages: ['kk', 'ru'],
    name: { kk: 'Педагогика және психология', ru: 'Педагогика и психология', en: 'Pedagogy & Psychology' },
    description: {
      kk: 'Оқыту әдістемесі, балалар психологиясы және білім беру технологиялары.',
      ru: 'Методика преподавания, детская психология и образовательные технологии.',
      en: 'Teaching methodology, child psychology, and educational technologies.',
    },
  },
  {
    id: 'law',
    faculty: 'law',
    degree: 'bachelor',
    credits: 240,
    duration: 4,
    languages: ['kk', 'ru'],
    name: { kk: 'Құқықтану', ru: 'Юриспруденция', en: 'Law' },
    description: {
      kk: 'Азаматтық, қылмыстық және әкімшілік құқық, сот жүйесі және заңнама.',
      ru: 'Гражданское, уголовное и административное право, судебная система и законодательство.',
      en: 'Civil, criminal, and administrative law, judicial system and legislation.',
    },
  },
  {
    id: 'tourism',
    faculty: 'humanities',
    degree: 'bachelor',
    credits: 240,
    duration: 4,
    languages: ['kk', 'ru', 'en'],
    name: { kk: 'Туризм', ru: 'Туризм', en: 'Tourism' },
    description: {
      kk: 'Туристік бизнесті басқару, қонақүй шаруашылығы және мәдени мұра.',
      ru: 'Управление туристическим бизнесом, гостиничное хозяйство и культурное наследие.',
      en: 'Tourism business management, hospitality, and cultural heritage.',
    },
  },
] as const;
