import type { StudentProfile, SkillMapNode, SkillMapEdge } from '@/types';

export const STUDENTS: StudentProfile[] = [
  {
    id: 'aibek-nurlan',
    name: 'Айбек Нурланов',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
    major: {
      kk: 'Тау-кен ісі',
      ru: 'Горное дело',
      en: 'Mining Engineering',
    },
    faculty: 'mining-tech',
    year: 4,
    gpa: 3.87,
    classRank: 'Top 5%',
    englishLevel: 'IELTS 7.0',
    internships: 3,
    summary: {
      kk: 'Тау-кен инженериясы бойынша 4-курс студенті. Кен орындарын жобалау және қауіпсіздік жүйелерін оңтайландыруға маманданған. «Казахмыс» компаниясында тау-кен инженері болып тағылымдамадан өткен.',
      ru: 'Студент 4 курса по горному делу. Специализируется на проектировании рудников и оптимизации систем безопасности. Проходил стажировку в «Казахмыс» в качестве горного инженера.',
      en: 'Fourth-year Mining Engineering student specializing in mine design and safety system optimization. Completed internship at Kazakhmys as a mining engineer.',
    },
    skills: [
      { label: 'Technical', value: 92 },
      { label: 'Analytical', value: 88 },
      { label: 'Leadership', value: 75 },
      { label: 'Communication', value: 70 },
      { label: 'Innovation', value: 85 },
    ],
    competencies: [
      {
        name: { kk: 'Mine Planning & Design', ru: 'Проектирование шахт', en: 'Mine Planning & Design' },
        percentage: 95,
        color: '#3B82F6',
      },
      {
        name: { kk: 'Safety Systems', ru: 'Системы безопасности', en: 'Safety Systems' },
        percentage: 90,
        color: '#22C55E',
      },
      {
        name: { kk: 'AutoCAD / Mining Software', ru: 'AutoCAD / ПО для горного дела', en: 'AutoCAD / Mining Software' },
        percentage: 88,
        color: '#E6B325',
      },
      {
        name: { kk: 'Geological Analysis', ru: 'Геологический анализ', en: 'Geological Analysis' },
        percentage: 82,
        color: '#8B5CF6',
      },
    ],
    achievements: [
      {
        id: 'ach-1',
        title: {
          kk: 'Республикалық олимпиада — I орын',
          ru: 'Республиканская олимпиада — I место',
          en: 'National Olympiad — 1st Place',
        },
        issuer: {
          kk: 'ҚР Білім министрлігі',
          ru: 'Министерство образования РК',
          en: 'Ministry of Education RK',
        },
        date: '2025-03',
        icon: 'Trophy',
        verified: true,
      },
      {
        id: 'ach-2',
        title: {
          kk: 'Үздік ғылыми мақала',
          ru: 'Лучшая научная статья',
          en: 'Best Research Paper',
        },
        issuer: {
          kk: 'ZhezU ғылыми кеңесі',
          ru: 'Научный совет ZhezU',
          en: 'ZhezU Scientific Council',
        },
        date: '2025-05',
        icon: 'FileText',
        verified: true,
      },
      {
        id: 'ach-3',
        title: {
          kk: 'Kazakhmys тағылымдамасы',
          ru: 'Стажировка в Казахмыс',
          en: 'Kazakhmys Internship',
        },
        issuer: {
          kk: 'Kazakhmys Corporation',
          ru: 'Казахмыс Корпорейшн',
          en: 'Kazakhmys Corporation',
        },
        date: '2025-07',
        icon: 'Briefcase',
        verified: true,
      },
    ],
    portfolio: [
      {
        id: 'port-1',
        title: {
          kk: 'Терең кен орнын жобалаудың оңтайландырылуы',
          ru: 'Оптимизация проектирования глубоких рудников',
          en: 'Deep Mine Design Optimization',
        },
        description: {
          kk: 'Терең кен орындарында қауіпсіздікті арттыру және шығындарды азайту бойынша зерттеу.',
          ru: 'Исследование по повышению безопасности и снижению затрат в глубоких рудниках.',
          en: 'Research on improving safety and reducing costs in deep mine operations.',
        },
        type: 'research',
        date: '2025-04',
      },
      {
        id: 'port-2',
        title: {
          kk: 'Жасанды интеллект негізіндегі кен барлау жүйесі',
          ru: 'AI-система разведки месторождений',
          en: 'AI-Driven Mineral Exploration System',
        },
        description: {
          kk: 'Геологиялық деректерді талдайтын машиналық оқыту моделі.',
          ru: 'Модель машинного обучения для анализа геологических данных.',
          en: 'Machine learning model for analyzing geological survey data.',
        },
        type: 'project',
        date: '2025-06',
      },
    ],
    matchScore: 95,
    tags: ['Mining', 'Safety', 'AutoCAD', 'Geology', 'Leadership'],
    email: 'a.nurlan@zhezu.edu.kz',
    linkedin: 'https://linkedin.com/in/aibek-nurlan',
  },
  {
    id: 'dana-serik',
    name: 'Дана Серікова',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
    major: {
      kk: 'Металлургия',
      ru: 'Металлургия',
      en: 'Metallurgy',
    },
    faculty: 'mining-tech',
    year: 3,
    gpa: 3.92,
    classRank: 'Top 3%',
    englishLevel: 'IELTS 7.5',
    internships: 2,
    summary: {
      kk: 'Металлургия бағытының 3-курс студенті. Қорытпалар технологиясы мен материалтану бойынша маманданады.',
      ru: 'Студентка 3 курса металлургии. Специализируется на технологии сплавов и материаловедении.',
      en: 'Third-year Metallurgy student specializing in alloy technology and materials science.',
    },
    skills: [
      { label: 'Technical', value: 90 },
      { label: 'Analytical', value: 95 },
      { label: 'Leadership', value: 72 },
      { label: 'Communication', value: 80 },
      { label: 'Innovation', value: 88 },
    ],
    competencies: [
      {
        name: { kk: 'Materials Science', ru: 'Материаловедение', en: 'Materials Science' },
        percentage: 94,
        color: '#3B82F6',
      },
      {
        name: { kk: 'Alloy Technology', ru: 'Технология сплавов', en: 'Alloy Technology' },
        percentage: 91,
        color: '#22C55E',
      },
      {
        name: { kk: 'Lab Research', ru: 'Лабораторные исследования', en: 'Lab Research' },
        percentage: 89,
        color: '#E6B325',
      },
      {
        name: { kk: 'Data Analysis', ru: 'Анализ данных', en: 'Data Analysis' },
        percentage: 85,
        color: '#8B5CF6',
      },
    ],
    achievements: [
      {
        id: 'ach-d1',
        title: {
          kk: 'Ғылыми грант иегері',
          ru: 'Обладатель научного гранта',
          en: 'Research Grant Recipient',
        },
        issuer: {
          kk: 'ҚР ҒЖБМ',
          ru: 'МНВО РК',
          en: 'MSHE RK',
        },
        date: '2025-01',
        icon: 'Award',
        verified: true,
      },
    ],
    portfolio: [
      {
        id: 'port-d1',
        title: {
          kk: 'Мыс қорытпаларының микроқұрылымдық талдауы',
          ru: 'Микроструктурный анализ медных сплавов',
          en: 'Microstructural Analysis of Copper Alloys',
        },
        description: {
          kk: 'Жезқазған кен орнынан алынған мыс қорытпаларын зерттеу.',
          ru: 'Исследование медных сплавов из месторождений Жезказгана.',
          en: 'Study of copper alloys from Zhezkazgan deposits.',
        },
        type: 'research',
        date: '2025-03',
      },
    ],
    matchScore: 91,
    tags: ['Metallurgy', 'Materials', 'Research', 'Chemistry', 'Analysis'],
    email: 'd.serik@zhezu.edu.kz',
  },
  {
    id: 'timur-kasym',
    name: 'Тимур Касымов',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face',
    major: {
      kk: 'Электроэнергетика',
      ru: 'Электроэнергетика',
      en: 'Electrical Power Engineering',
    },
    faculty: 'mining-tech',
    year: 4,
    gpa: 3.75,
    classRank: 'Top 10%',
    englishLevel: 'IELTS 6.5',
    internships: 2,
    summary: {
      kk: 'Электроэнергетика бойынша 4-курс студенті. Энергия жүйелерін басқару мен жаңартылатын энергия көздеріне маманданған.',
      ru: 'Студент 4 курса электроэнергетики. Специализируется на управлении энергосистемами и возобновляемых источниках энергии.',
      en: 'Fourth-year Electrical Power Engineering student. Specializes in power systems management and renewable energy.',
    },
    skills: [
      { label: 'Technical', value: 85 },
      { label: 'Analytical', value: 82 },
      { label: 'Leadership', value: 78 },
      { label: 'Communication', value: 75 },
      { label: 'Innovation', value: 80 },
    ],
    competencies: [
      {
        name: { kk: 'Power Systems', ru: 'Энергосистемы', en: 'Power Systems' },
        percentage: 88,
        color: '#3B82F6',
      },
      {
        name: { kk: 'Renewable Energy', ru: 'Возобновляемая энергетика', en: 'Renewable Energy' },
        percentage: 85,
        color: '#22C55E',
      },
      {
        name: { kk: 'Circuit Design', ru: 'Проектирование схем', en: 'Circuit Design' },
        percentage: 82,
        color: '#E6B325',
      },
      {
        name: { kk: 'SCADA Systems', ru: 'SCADA системы', en: 'SCADA Systems' },
        percentage: 78,
        color: '#8B5CF6',
      },
    ],
    achievements: [
      {
        id: 'ach-t1',
        title: {
          kk: 'Энергетика бойынша хакатон жеңімпазы',
          ru: 'Победитель хакатона по энергетике',
          en: 'Energy Hackathon Winner',
        },
        issuer: {
          kk: 'KEGOC',
          ru: 'KEGOC',
          en: 'KEGOC',
        },
        date: '2025-04',
        icon: 'Zap',
        verified: true,
      },
    ],
    portfolio: [],
    matchScore: 87,
    tags: ['Energy', 'Electrical', 'Renewable', 'SCADA', 'Automation'],
    email: 't.kasym@zhezu.edu.kz',
  },
  {
    id: 'aliya-zhan',
    name: 'Алия Жанұзақова',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face',
    major: {
      kk: 'Құқықтану',
      ru: 'Юриспруденция',
      en: 'Law',
    },
    faculty: 'mining-tech',
    year: 3,
    gpa: 3.95,
    classRank: 'Top 2%',
    englishLevel: 'IELTS 7.5',
    internships: 1,
    summary: {
      kk: 'Құқықтану бағытының 3-курс студенті. Тау-кен құқығы мен экологиялық заңнамаға маманданады.',
      ru: 'Студентка 3 курса юриспруденции. Специализируется на горном праве и экологическом законодательстве.',
      en: 'Third-year Law student specializing in mining law and environmental legislation.',
    },
    skills: [
      { label: 'Technical', value: 70 },
      { label: 'Analytical', value: 93 },
      { label: 'Leadership', value: 85 },
      { label: 'Communication', value: 95 },
      { label: 'Innovation', value: 72 },
    ],
    competencies: [
      {
        name: { kk: 'Legal Analysis', ru: 'Правовой анализ', en: 'Legal Analysis' },
        percentage: 96,
        color: '#3B82F6',
      },
      {
        name: { kk: 'Mining Law', ru: 'Горное право', en: 'Mining Law' },
        percentage: 88,
        color: '#22C55E',
      },
      {
        name: { kk: 'Environmental Law', ru: 'Экологическое право', en: 'Environmental Law' },
        percentage: 85,
        color: '#E6B325',
      },
      {
        name: { kk: 'Public Speaking', ru: 'Ораторское искусство', en: 'Public Speaking' },
        percentage: 92,
        color: '#8B5CF6',
      },
    ],
    achievements: [
      {
        id: 'ach-a1',
        title: {
          kk: 'Мут-корт жарысы — II орын',
          ru: 'Мут-корт — II место',
          en: 'Moot Court — 2nd Place',
        },
        issuer: {
          kk: 'ҚР Заңгерлер одағы',
          ru: 'Союз юристов РК',
          en: 'Union of Lawyers RK',
        },
        date: '2025-02',
        icon: 'Scale',
        verified: true,
      },
    ],
    portfolio: [],
    matchScore: 83,
    tags: ['Law', 'Mining Law', 'Environment', 'Legal', 'Public Speaking'],
    email: 'a.zhan@zhezu.edu.kz',
  },
];

// Skill Map Data for Mining Engineering
export const SKILL_MAP_NODES: SkillMapNode[] = [
  // Center
  {
    id: 'major',
    label: { kk: 'Тау-кен ісі', ru: 'Горное дело', en: 'Mining Engineering' },
    x: 400,
    y: 300,
    type: 'major',
    size: 'lg',
    color: '#E6B325',
  },
  // UNT Scores (top)
  {
    id: 'unt-math',
    label: { kk: 'Математика', ru: 'Математика', en: 'Mathematics' },
    x: 250,
    y: 100,
    type: 'unt',
    size: 'md',
    color: '#3B82F6',
    value: '32/35',
  },
  {
    id: 'unt-physics',
    label: { kk: 'Физика', ru: 'Физика', en: 'Physics' },
    x: 400,
    y: 80,
    type: 'unt',
    size: 'md',
    color: '#3B82F6',
    value: '30/35',
  },
  {
    id: 'unt-chemistry',
    label: { kk: 'Химия', ru: 'Химия', en: 'Chemistry' },
    x: 550,
    y: 100,
    type: 'unt',
    size: 'md',
    color: '#3B82F6',
    value: '28/35',
  },
  // Hard Skills (left)
  {
    id: 'hard-autocad',
    label: { kk: 'AutoCAD', ru: 'AutoCAD', en: 'AutoCAD' },
    x: 120,
    y: 220,
    type: 'hard',
    size: 'sm',
    color: '#22C55E',
  },
  {
    id: 'hard-surpac',
    label: { kk: 'Surpac', ru: 'Surpac', en: 'Surpac' },
    x: 100,
    y: 320,
    type: 'hard',
    size: 'sm',
    color: '#22C55E',
  },
  {
    id: 'hard-geostat',
    label: { kk: 'Геостатистика', ru: 'Геостатистика', en: 'Geostatistics' },
    x: 140,
    y: 420,
    type: 'hard',
    size: 'sm',
    color: '#22C55E',
  },
  {
    id: 'hard-safety',
    label: { kk: 'Қауіпсіздік жүйелері', ru: 'Системы безопасности', en: 'Safety Systems' },
    x: 200,
    y: 500,
    type: 'hard',
    size: 'md',
    color: '#22C55E',
  },
  // Soft Skills (right)
  {
    id: 'soft-leadership',
    label: { kk: 'Көшбасшылық', ru: 'Лидерство', en: 'Leadership' },
    x: 660,
    y: 200,
    type: 'soft',
    size: 'sm',
    color: '#8B5CF6',
  },
  {
    id: 'soft-teamwork',
    label: { kk: 'Команда жұмысы', ru: 'Командная работа', en: 'Teamwork' },
    x: 700,
    y: 310,
    type: 'soft',
    size: 'sm',
    color: '#8B5CF6',
  },
  {
    id: 'soft-problem',
    label: { kk: 'Мәселені шешу', ru: 'Решение проблем', en: 'Problem Solving' },
    x: 680,
    y: 420,
    type: 'soft',
    size: 'sm',
    color: '#8B5CF6',
  },
  // Career Paths (bottom)
  {
    id: 'career-engineer',
    label: { kk: 'Тау-кен инженері', ru: 'Горный инженер', en: 'Mining Engineer' },
    x: 250,
    y: 530,
    type: 'career',
    size: 'md',
    color: '#F59E0B',
  },
  {
    id: 'career-safety-officer',
    label: { kk: 'Қауіпсіздік менеджері', ru: 'Менеджер по безопасности', en: 'Safety Manager' },
    x: 400,
    y: 560,
    type: 'career',
    size: 'md',
    color: '#F59E0B',
  },
  {
    id: 'career-geologist',
    label: { kk: 'Геолог', ru: 'Геолог', en: 'Geologist' },
    x: 550,
    y: 530,
    type: 'career',
    size: 'md',
    color: '#F59E0B',
  },
];

export const SKILL_MAP_EDGES: SkillMapEdge[] = [
  // Major to UNT
  { from: 'major', to: 'unt-math' },
  { from: 'major', to: 'unt-physics' },
  { from: 'major', to: 'unt-chemistry' },
  // Major to Hard Skills
  { from: 'major', to: 'hard-autocad' },
  { from: 'major', to: 'hard-surpac' },
  { from: 'major', to: 'hard-geostat' },
  { from: 'major', to: 'hard-safety' },
  // Major to Soft Skills
  { from: 'major', to: 'soft-leadership' },
  { from: 'major', to: 'soft-teamwork' },
  { from: 'major', to: 'soft-problem' },
  // Major to Careers
  { from: 'major', to: 'career-engineer' },
  { from: 'major', to: 'career-safety-officer' },
  { from: 'major', to: 'career-geologist' },
  // Cross-connections
  { from: 'hard-safety', to: 'career-safety-officer' },
  { from: 'hard-autocad', to: 'career-engineer' },
  { from: 'hard-geostat', to: 'career-geologist' },
  { from: 'unt-math', to: 'hard-geostat' },
  { from: 'unt-physics', to: 'hard-safety' },
];
